connectionHandler:
  handler: handler.connectionHandler
  events:
    - websocket:
        route: $connect
    - websocket:
        route: $disconnect
defaultHander:
  handler: handler.defaultHandler
  events:
    - websocket:
        route: $default
sendMessageHandler:
  handler: handler.sendMessageHandler
  events:
    - websocket:
        route: sendMessage
