ChatTable:
  Type: "AWS::DynamoDB::Table"
  Properties:
    TableName: chatIdTable
    AttributeDefinitions:
      - AttributeName: "connectionId"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "connectionId"
        KeyType: "HASH"
    BillingMode: PAY_PER_REQUEST
